# -*- coding: utf-8 -*-
"""Prueba.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BUKDj7n9wHHADNr_eLeGmBeiMBfjjSyC
"""

def suma(n1,n2):
  suma = n1 + n2 
  return(suma)